version: '3.8'

services:
  app:
    build: .
    command: sh -c 'uvicorn api.main:app --host 0.0.0.0 --port 8000'
    volumes:
      - .:/home/appuser
      - shared_output:/home/appuser/output
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A api.services.celery_app worker --loglevel=info --concurrency=1
    volumes:
      - .:/home/appuser
      - shared_output:/home/appuser/output
    env_file:
      - .env
    depends_on:
      - redis
      - app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://app:8000
    depends_on:
      - app

volumes:
  redis_data:
  shared_output:
