version: '3.8'

services:
  app:
    build: .
    command: sh -c 'uvicorn api.main:app --host 0.0.0.0 --port 8000'
    volumes:
      - .:/home/appuser
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A api.services.celery_app worker --loglevel=info --concurrency=1
    volumes:
      - .:/home/appuser
    env_file:
      - .env
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A api.services.celery_app beat --loglevel=info --concurrency=1
    volumes:
      - .:/home/appuser
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 