[tool.black]
line-length = 88
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["api"]
skip = [".venv", "venv", "env", "build", "dist", "migrations"] 