[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.17.0"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://web-production-23301.up.railway.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://web-production-23301.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 